markdown: kramdown
safe: false
permalink: /blog/posts/:title
baseurl: /myblog
exclude:
  - README.md

blog:
    host: wilsonis.github.io/myblog
    name: 月溅星河长路漫漫
    desc: 读读写写

custom:
    category:
        thinking: Why...
        experience: How To Do
        discovery: What's New
        criticism: What's Wrong
        communication: Sharing Is Something
    categories:
      - name:  thinking
        title: Why...

      - name:  experience
        title: How To Do

      - name:  discovery
        title: What's New

      - name:  criticism
        title: What's Wrong

      - name: communication
        title: Sharing Is Something

    scrollingLoadCount: 2                          # 滚屏自动加载文章数量，“0”为关闭

meta:
    author:
        name: wilsonIsOnly
        email: zhangtao522009@163.com
        disqus: comments                            # Disqus缩略标识
        gcse: 000346898720731947188:13h55x32l0y     # Google自定义搜索标识ID
        github: wilsonIs                            # GitHub账号
        gravatar: da684d962367463945d2693ab82d3410  # Gravatar头像标识

    disqus: disqus.com/embed.js                     # Disqus评论的JS地址
    gapi: http://www.google.com/jsapi               # Google API地址
    gravatar: http://en.gravatar.com/avatar/        # Gravatar头像服务器地址
